zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "2182:2181"
kafka:
  image: wurstmeister/kafka:0.10.2.1
  ports:
    - "9093:9093"
  links:
    - zookeeper:zk
  environment:
    KAFKA_PORT: 9093
    KAFKA_BROKER_ID: 1
    KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
    KAFKA_CREATE_TOPICS: "test:1:1,__cross_datacenter_replication:1:1"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
