zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "2181:2181"
kafka:
  image: wurstmeister/kafka:0.10.2.1
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_BROKER_ID: 1
    KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
    KAFKA_CREATE_TOPICS: "test:10:1,__cross_datacenter_replication:1:1"
    KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
